---
- name: "Creates main path of containers host volumes"
  file:
    path: "{{ ENV_MAIN_PATH }}"
    state: directory
    recurse: yes


- name: "Creates directory"
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ ENV_RUNDECK_PATH_RESOURCES }}"
    - "{{ ENV_RUNDECK_PATH_PROJECTS }}"
    - "{{ ENV_RUNDECK_PATH_SERVER }}"
    - "{{ ENV_RUNDECK_PATH_SSH }}"

# TODO: Templating files for rundeck